### ISSUE TITLE
Minor correction

### ISSUE THREAD

**Issue by Dougoll** [sir-wilhelm/d2r-handle-closer#1]
Hi!

On the line 14, it has to be **.\handle.exe** instead of **handle** 

Before correction (line 14)
handle -c $eventHandle -p $d2pid -y -nobanner

After correction (line 14)
.\handle.exe -c $eventHandle -p $d2pid -y -nobanner

Have a good one! Thanks for the tool, really useful!

**Comment by sir-wilhelm** [comment]
Ahh ya, left overs from when I was adding the local script path to the system path and just calling handle. 

I guess the PowerShell instance I was running still had that path change, so both calls were working -- I'm sure I would have found the issue after a reboot for windows updates :D.

The fix is pushed, I'm glad you are enjoying it.
